### ISSUE TITLE
stillinbeta.se länkar

### ISSUE THREAD

**Issue by MikaelPorttila** [kodsnack/site#21]
Yo, Domänen stillinbeta.se ser för tillfället inte ut att ha någon ägare och ni länkar till domänen på er sajt, peka om urlarna eller ta över domänen innan något troll köper den och fyller den med irrelevant innehåll.

**Comment by simskij** [comment]
Bra tanke! Nu pekar URL:n på LeoVegas

**Comment by bjoreman** [comment]
Jag tog helt enkelt bort länkarna, det kändes rakast och enklast.
